version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: surgery_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d surgery_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./BackEnd
    container_name: backend_python
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
    env_file:
      - ./BackEnd/.env
    depends_on:
      db:
        condition: service_healthy
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  frontend:
    build: ./Frontend
    container_name: frontend_react
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  pg_data: